CREATE TABLE usuario (
	id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(30) NOT NULL,
	whatsapp VARCHAR(20) NOT NULL,
	professor VARCHAR(8) NOT NULL
);
