CREATE TABLE aula (
	id_aula INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tituloAula VARCHAR(100) NOT NULL,
	video VARCHAR(100) NOT NULL,
	texto VARCHAR(100) NOT NULL,
	exercicio VARCHAR(100) NOT NULL
);

