CREATE TABLE curso (
	id_curso INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR(100) NOT NULL,
	assunto VARCHAR(100) NOT NULL,
	descricao VARCHAR(100) NOT NULL,
	conteudo VARCHAR(100) NOT NULL

	
);
